testname: webMUSHRA Decoder Listening Test
testId: Ambisonic_Decoder_Test
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: >
        Welcome to the Ambisonic Decoder Listening Test <br/>
        There are halves to this test. Part 1 is based on tracks containing sound source characteristics <br/>
        while part 2 will be based around more environmental characteristics. <br/>
        Once all tests are finished, please fill ot the questinonnaire and submit the results <br/>
        You may take a break or pull out from doing the test at any moment <br/>
        Thank you! <br/>
        
    - type: generic
      id: Instructions
      name: Instructions
      content: > 
        This is the first half of the test. This half will test three different characteristics; <br/>
        Localisation accuracy, Localisation and Apparent Source width <br/> <br/>
        For each characteristic there will be an available reference on the left hand side of the page which you can listen to at any time. <br/>
        There will be a number of audio files for you to listen to which must be rated from 0-100 using the associated sliders. <br/>
        This rating should be based on how similar the selected audio file is to the reference file for the given characteristic. <br/>
        A rating of 0 would describe the chosen file as pure noise and a rating of 100 would state the file has no difference to the available reference. <br/> <br/>
        Please ensure to compare the selected track against the REFERENCE ONLY and not to the other audio files. <br/> <br/>
        There are also two sliders under the waveform of the audio file. <br/>
        These can be dragged at any time to listen to certain points of the audio file in a looped fashion. <br/>
        
        
    - type: mushra
      id: distCube1
      name: EXTERNALISATION - CUBE LAYOUT
      content: Please rate the test files from 0-100 on how similar the externalisation of the track is to the available reference.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/externalisation/marsh_ref.wav 
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/externalisation/cube/marsh_allrad.wav 
          C2: configs/resources/audio/externalisation/cube/marsh_DTS.wav 
          C3: configs/resources/audio/externalisation/cube/marsh_Harpex.wav